### ISSUE TITLE
Cannot remove/move spells on actionbar

### ISSUE THREAD

**Issue by ultimaplayer12** [cogwerkz/DiabolicUI#126]
**Description**
Vanilla WoW allows you to move the spells around on the action bar when unlocked, or when holding shift. However with this UI enabled, this feature is seemingly disabled.

**Version Number**
1.3.114-Release

**Steps to Reproduce**

None

**Expected Behavior**
When the action bars are unlocked, or SHIFT is held down, spells in the action bar should be movable.

**Actual Behavior**
Whether action bars are locked/unlocked, or SHIFT is held, nothing happens.

**Only DiabolicUI Enabled**
This is not an issue with the vanilla HUD or any other addons I have, the issue only arrives when I enable DiabolicUI.

**Comment by goldpaw** [comment]
Not a bug. Hold down ctrl+alt+shift at the same time, then drag with the mouse button. It has its own switch, it doesn't follow the blizz keys for it.

**Comment by ultimaplayer12** [comment]
I noticed this after digging more around the UI. I have two points to make about this 1) it should be more clear in the HUD if this is a change you're going to make. 2) said hotkeys still "use" the ability when you go to remove it, that should be resolved or the hotkey should be put back to default.

**Comment by goldpaw** [comment]
Well it's written at the bottom of the window where you toggle the number of actionbars. But I'll figure out a way to make it more clear. :) 

Spells being cast when clicking them is not a bug though, it's a blizzard setting not related to this or any other addon. It used to be part of the standard blizzard interface menu, but they removed it from the menu in Legion, though the setting still exists. Can still be changed in-game through some commands, though: 

https://github.com/cogwerkz/DiabolicUI/wiki/Frequently-Asked-Questions
Cast on key release:
```
/run SetCVar("ActionButtonUseKeyDown", 0); ReloadUI()
```
Cast on key down:
```
/run SetCVar("ActionButtonUseKeyDown", 1); ReloadUI()
```
