### ISSUE TITLE
Spellflash when procc at Actionbar  (bug?) | bar without function in mythic plus dungeons

### ISSUE THREAD

**Issue by AntonyMcLovin** [cogwerkz/DiabolicUI#37]
Hi there, 

I have a question cause I have no addon for this and I don't think that this bug is caused from vanilla ui. 

see screenshot: 
https://picload.org/image/rlodilia/wowscrnshot_030517_101933.jpg

when I get a procc like gettin mana back from healing tuch (see screenshot) the wrong spells starts to flash at my bar (in this case solar wrath). 

Do you know if there is some kind of spellflash integrated in your UI? Otherwise I have to start looking at other addons. 

and by the way: as you can see in the middle of the screen there is a grey bar without any function. It always appears in mythic + dungeons... Is there any future purpose for this? Is this a known issue? I can make a separate ticket for that

**Comment by goldpaw** [comment]
fixed in 1.1.32

**Comment by AntonyMcLovin** [comment]
Bug with procc and starsurge: http://de.wowhead.com/spell=78674/

when using starsurge and gettin 2x buffs (Solar Empowerment and Lunar Empowerment http://de.wowhead.com/spell=164545
http://de.wowhead.com/spell=164547

When using Lunar strike with both buffs active the spellflash animation for Solar wrath vanishes altough the  solar empowerment buffs still exists. 

When using solar wrath with both buffs active the spellflash animation for solar wrath stays altough there is no buff for solar wrath, just for lunar strike.
